#!/bin/sh

[ "$CONSUL" = "no" ] && sv stop "$PWD"

GWDEV="$(ip route list 0/0 | awk '{print $NF}')"

ADVERTISE="${ADVERTISE:-$(ip -f inet -o a s | awk -F " +|/" "\$2 != \"lo\" && \$2 != \"$GWDEV\" {print \$4; exit(0)}")}"

# write our config file
cat << dog > /consul.json
{
	"bootstrap_expect": $CONSUL_BOOTSTRAP_EXPECT,
	"datacenter": "$CONSUL_DATACENTER",
	"domain": "$CONSUL_DOMAIN",
	"server": true,
	"data_dir": "/consul",
	"client_addr": "0.0.0.0",
	"advertise_addr": "$ADVERTISE",
	"retry_interval": "10s",
	"leave_on_terminate": true,
dog
if [ -n "$CONSUL_JOIN" ]; then
	echo "	\"retry_join\": [\"$(echo "$CONSUL_JOIN" | sed -e 's/ /","/g')\"]," >> /consul.json
fi
if [ -n "$CONSUL_RECURSORS" ]; then
	echo "	\"recursors\": [\"$(echo "$CONSUL_RECURSORS" | sed -e 's/ /","/g')\"]," >> /consul.json
fi
if [ -n "$CONSUL_WAN" ]; then
	echo "	\"retry_join_wan\": [\"$(echo "$CONSUL_WAN" | sed -e 's/ /","/g')\"]," >> /consul.json
fi
cat << dog >> /consul.json
	"ports": {
		"dns": $CONSUL_PORT_DNS
	},
	"ui_dir": "/webui"
}
dog

exec /bin/consul agent -config-file /consul.json ${CONSUL_ARGS:-}
